node:
  build: .
  #  restart: always
  command: node ./bin/www DEBUG=accountant:*
  environment:
    NODE_ENV: staging
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/accountant
    - /home/app/accountant/node_modules
  links:
   - postgres
postgres:
  #  restart: always
  image: postgres
  environment:
    - POSTGRES_USER=accountant
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=accountant_staging
  volumes_from:
    - accountant_data

