node:
  build: .
  #  restart: always
  command: node ./bin/www DEBUG=skeleton:*
  environment:
    NODE_ENV: staging
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/skeleton
    - /home/app/skeleton/node_modules
  links:
   - postgres
postgres:
  #  restart: always
  image: postgres
  environment:
    - POSTGRES_USER=skeleton
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=skeleton_staging
  volumes_from:
    - skeleton_data

