node:
  build: .
  command: node ./bin/www DEBUG=skeleton:*
  environment:
    NODE_ENV: staging
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/skeleton
    - /home/app/skeleton/node_modules
  links:
   - mongo
mongo:  
  image: mongo #:3.0.4
  volumes_from:
    - skeleton_mongo_data
  ports:
    - "27017"
  command: --smallfiles #--rest --auth
