nginx:
  image: nginx
  restart: always
  environment:
    - VIRTUAL_HOST=chocobuttons.com
    - LETSENCRYPT_HOST=chocobuttons.com
    - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
  volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
  links:
    - node-app:node-app
node-app:
  build: .
  restart: always
  command: node ./bin/www
  environment:
    NODE_ENV: production
  ports:
    - '3000'
  volumes:
    - .:/home/app/skeleton
    - /home/app/skeleton/node_modules
  links:
   - mongo
mongo:  
  image: mongo
  volumes_from:
    - skeleton_mongo_data
  ports:
    - "27017"
  command: --smallfiles #--rest --auth
